# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI with ccache

on:
  schedule:
    - cron: 0 20 * * *
  watch:
    types: [started]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: self-hosted

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'coolsnowwolf/lede'
          ref: master
          fetch-depth: 0

      - name: cache
        uses: klever1988/hello-world-javascript-action@main
        with:
          skip: 'false'

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          nohup sh -c 'sudo -E apt-get update
          sudo -E apt-get -y --no-upgrade install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          docker rmi `docker images -q`
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean' &

          df -h

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' > .config
          make defconfig
          grep -i ccache .config

      - name: Make download
        run: |
          make download -j
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          #make toolchain/compile -j$[`nproc`+1]
          #make tools/compile -j$[`nproc`+1]
          #make target/compile -j$[`nproc`+1]
          make -j$[`nproc`+1]
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
